/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.UserDAO;
import javax.swing.JOptionPane;
import object.User;
import view.Label.ManageLabel;
import view.Pattern.ManagePattern;

/**
 *
 * @author nguyenvannghiem
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public AdminView() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btLabelProduct = new javax.swing.JButton();
        btLabelProperty = new javax.swing.JButton();
        btLabelQuality = new javax.swing.JButton();
        btPatternProduct = new javax.swing.JButton();
        btPatternProperty = new javax.swing.JButton();
        btPatternQuality = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản trị viên");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("HỆ THỐNG HỖ TRỢ THAM KHẢO PHẢN HỒI CỦA KHÁCH HÀNG VỀ SẢN PHẨM");

        btLabelProduct.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btLabelProduct.setText("Quản lý nhãn sản phẩm");
        btLabelProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLabelProductActionPerformed(evt);
            }
        });

        btLabelProperty.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btLabelProperty.setText("Quản lý nhãn thuộc tính");
        btLabelProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLabelPropertyActionPerformed(evt);
            }
        });

        btLabelQuality.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btLabelQuality.setText("Quản lý nhãn chất lượng");
        btLabelQuality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLabelQualityActionPerformed(evt);
            }
        });

        btPatternProduct.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btPatternProduct.setText("Quản lý  mẫu sản phẩm");
        btPatternProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPatternProductActionPerformed(evt);
            }
        });

        btPatternProperty.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btPatternProperty.setText("Quản lý mẫu thuộc tính");
        btPatternProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPatternPropertyActionPerformed(evt);
            }
        });

        btPatternQuality.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btPatternQuality.setText("Quản lý mẫu chất lượng");
        btPatternQuality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPatternQualityActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("QUẢN LÝ HẬU CẦN CỦA SERVER");

        btLogout.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btLogout.setText("Đăng xuất");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLabelProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLabelQuality, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLabelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPatternProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPatternQuality, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPatternProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(btLogout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btLabelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(btLabelProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btLabelQuality, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPatternProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btPatternProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btPatternQuality, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(btLogout)
                .addGap(219, 219, 219))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLabelProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLabelProductActionPerformed
        // TODO add your handling code here:
        String loaiNhan = "Product";
        ManageLabel ml = new ManageLabel(loaiNhan);
        ml.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btLabelProductActionPerformed

    private void btLabelPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLabelPropertyActionPerformed
        // TODO add your handling code here:
        String loaiNhan = "Property";
        ManageLabel ml = new ManageLabel(loaiNhan);
        ml.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btLabelPropertyActionPerformed

    private void btLabelQualityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLabelQualityActionPerformed
        // TODO add your handling code here:
        String loaiNhan = "Quality";
        ManageLabel ml = new ManageLabel(loaiNhan);
        ml.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btLabelQualityActionPerformed

    private void btPatternProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPatternProductActionPerformed
        // TODO add your handling code here:
        String loaiMau = "Product";
        ManagePattern mp = new ManagePattern(loaiMau);
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btPatternProductActionPerformed

    private void btPatternPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPatternPropertyActionPerformed
        // TODO add your handling code here:
        String loaiMau = "Property";
        ManagePattern mp = new ManagePattern(loaiMau);
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btPatternPropertyActionPerformed

    private void btPatternQualityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPatternQualityActionPerformed
        // TODO add your handling code here:
        String loaiMau = "Quality";
        ManagePattern mp = new ManagePattern(loaiMau);
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btPatternQualityActionPerformed

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Đăng xuất?","Xác nhận",JOptionPane.YES_NO_OPTION);
        if(result==JOptionPane.YES_OPTION){
            this.dispose();
            HomeView hv = new HomeView();
            hv.setVisible(true);
        } 
    }//GEN-LAST:event_btLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLabelProduct;
    private javax.swing.JButton btLabelProperty;
    private javax.swing.JButton btLabelQuality;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btPatternProduct;
    private javax.swing.JButton btPatternProperty;
    private javax.swing.JButton btPatternQuality;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
